version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./magento:/var/www/magento
      - ./site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

  php:
    image: php:7.2-fpm
    volumes:
    - ./magento:/var/www/magento