version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - "6000:80"
    volumes:
      - ./magento:/var/www/magento
      - ./site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build:
      context: ./dockerfiles
      dockerfile: php73fpm-DockerFile
    volumes:
    - ./magento:/var/www/magento
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: "always"
    environment:
      MYSQL_ROOT_PASSWORD: mysql_root_pwd
      MYSQL_DATABASE: magento2
      MYSQL_USER: magento2_user
      MYSQL_PASSWORD: magento2_pwd
    volumes:
      - ./database:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      MYSQL_USER: magento2_user
      MYSQL_PASSWORD: magento2_pwd
      MYSQL_ROOT_PASSWORD: mysql_root_pwd
      PMA_PORT: 3306
      PMA_HOST: mysql
    ports:
      - "6969:80"
    depends_on:
      - php
      - mysql

  composer:
    image: composer
    restart: "always"
    volumes:
    - ./magento:/var/www/magento
    command: install
    depends_on:
    - web
    - php
    working_dir: /var/www/magento